baseurl:/jekyllDemo

title: Jeffrey's Blog

author : Jeffrey

name : Name Lastname

email : kinsungchan@gmail.com

github : https://github.com/JeffreyDChan

WeChat : dou2011668

LinkedIn : https://cn.linkedin.com/in/¶¼-³Â-ab4262119
